# Define the services (containers) that make up your application.
services:
  # --- NEW SERVICE: API---
  api:
    build: api
    container_name: api
    secrets:
      - DB_FILE
      - JWT_SECRET
      - JWT_ALGORITHM
      - TOKEN_EXPIRE
      - SECRET_SERVER_PEPPER
    env_file:
      - ./API/secrets.env
    ports:
      - "8000:8000"
    expose:
      - "8000"
    command: uvicorn API:app --host 0.0.0.0 --port 8000
    networks:
      projectNetwork:
        ipv4_address: 172.2.2.4
    volumes:
      - vault_data:/app/database

secrets:
  DB_FILE:
    file: ./API/secrets/db_file_path.txt
  JWT_SECRET:
    file: ./API/secrets/jwt_secret_key.txt
  JWT_ALGORITHM:
    file: ./API/secrets/jwt_algorithm.txt
  TOKEN_EXPIRE:
    file: ./API/secrets/token_expire.txt
  SECRET_SERVER_PEPPER:
    file: ./API/secrets/secret_server_pepper.txt

networks:
  projectNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.2.2.0/28"

volumes:
  vault_data: